### ISSUE TITLE
Not connect its all IPs if backend with hostname have multiple IP addresses

### ISSUE THREAD

**Issue by ochinchina** [ochinchina/thriftproxy#5]
In a proxy configuration, if the backend is a hostname and the hostname have multiple IPs, the thriftproxy does not connect all its IPs.

For example there is a backend "test-host:9091" in the proxy "test-1". The backend is not in "ip:port" format, it is in "hostname:port" format. And the host "test-host" have multiple IP addresses, but the thriftproxy only make a connection to only one of its IP addresses, not make connection to all its IP adddresses.

```yaml
proxies:
  - name: test-1 
    listen: ":9090"
    backends:
      - "test-host:9091"
```
